CREATE TABLE Questions (question TEXT, priority INTEGER PRIMARY KEY);
INSERT INTO Questions VALUES ("When Is Recces", 4);
INSERT INTO Questions VALUES ("When is lunch", 3);
INSERT INTO Questions VALUES ("What classes do I have", 2);
INSERT INTO Questions VALUES ("Am I in the same classes as my friends", 1);
INSERT INTO Questions VALUES ("When is PE", 6);
INSERT INTO Questions VALUES ("How many kids per class", 7);
INSERT INTO Questions VALUES ("Do we have computers", 8);
INSERT INTO Questions VALUES ("Do we have lockers or desks", 5);
SELECT * FROM Questions;
CREATE TABLE answers (answer TEXT, qid INTEGER PRIMARY KEY);
